name: Deploy to All-Inkl

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Deploy to All-Inkl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to All-Inkl
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 30
          shell: bash
          command: |
            npx ftp-deploy --user "${{ secrets.PRD_USER }}" --password "${{ secrets.PRD_PASSWORD }}" --host "${{ secrets.PRD_HOST }}" --port 21 --local-root "." --server-root "/" --exclude ".git/" --exclude "node_modules/" --exclude ".DS_Store" --delete --verbose
